import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Blogs Detail',
    description: 'Generated by create next app',
}

export default function ViewDetailLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>
    )
}
