// import './globals.css'
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Blogs List',
    description: 'Generated by create next app',
}

export default function BlogLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>
    )
}
